# defaults: &defaults
#   machine:
#     services:
#       - docker
#   steps:
#   - checkout
#   - run:
#       name: "Setup required directories"
#       command: |
#         mkdir -p /tmp/apache-cloudstack
#         mkdir -p /tmp/.m2
#   - restore_cache:
#       key: repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-m2
#   - run:
#       name: "Build Docker image"
#       command: make ${TAG}
#   - run:
#       name: "Test Docker image"
#       command: |
#         docker run \
#           --volume /tmp/apache-cloudstack:/mnt/build \
#           --volume /tmp/.m2:/root/.m2 \
#           --rm \
#           ${IMAGE}:${TAG} \
#             --git-remote ${BUILD_REPO} \
#             --git-ref ${BUILD_REF} \
#             --remove-first \
#             ${BUILD_PARAMS}
#   - save_cache:
#       key: repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-m2
#       paths:
#         - /tmp/.m2

version: 2.1

jobs:
  test:
    parameters:
      image:
        type: string
      tag:
        type: string
      repo:
        type: string
      ref:
        type: string
      param:
        type: string
    machine:
      services:
        - docker
    steps:
    - checkout
    - run:
        name: "Test Docker image"
        command: |
          docker run \
            --volume /tmp/apache-cloudstack:/mnt/build \
            --volume /tmp/.m2:/root/.m2 \
            --rm \
            <<parameters.image>>:<<parameters.tag>> \
              --git-remote <<parameters.repo>> \
              --git-ref <<parameters.ref>> \
              --remove-first \
              <<parameters.param>>

  centos6:
    # <<: *defaults
    machine:
      services:
        - docker
    steps:
    - checkout
    - run:
        name: "Build Docker image"
        command: make ${TAG}
    environment:
      # IMAGE: khos2ow/cloudstack-rpm-builder
      TAG: centos6
      # BUILD_REPO: https://github.com/apache/cloudstack.git
      # BUILD_REF: refs/heads/4.13
      # BUILD_PARAMS: --distribution centos63

  # centos7:
  #   <<: *defaults
  #   environment:
  #     IMAGE: khos2ow/cloudstack-rpm-builder
  #     TAG: centos7
  #     BUILD_REPO: https://github.com/apache/cloudstack.git
  #     BUILD_REF: refs/heads/4.13
  #     BUILD_PARAMS: --distribution centos7

  # latest:
  #   <<: *defaults
  #   environment:
  #     IMAGE: khos2ow/cloudstack-rpm-builder
  #     TAG: centos7
  #     BUILD_REPO: https://github.com/apache/cloudstack.git
  #     BUILD_REF: refs/heads/4.13
  #     BUILD_PARAMS: --distribution centos7

workflows:
  version: 2
  build:
    # triggers:
    #   - branches:
    #     ignore: master
    jobs:
    - test:
        name: test-centos6
        image: khos2ow/cloudstack-rpm-builder
        tag: centos6
        repo: https://github.com/apache/cloudstack.git
        ref: refs/heads/4.13
        param: --distribution centos63
        requires:
        - centos6

    # - centos7:
    #     filters:
    #       branches:
    #         ignore: master

  # release:
  #   jobs:
  #   - centos6:
  #       filters:
  #         branches:
  #           only: master
  #           ignore: /.*/

  #   - centos7:
  #       filters:
  #         branches:
  #           only: master
  #           ignore: /.*/

  #   - latest:
  #       filters:
  #         branches:
  #           only: master
  #           ignore: /.*/

