version: 2.1

jobs:
  centos6:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: "Build Docker image"
        command: make centos6

  centos7:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: "Build Docker image"
        command: make centos7

  latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: "Build Docker image"
        command: make latest

  test:
    parameters:
      tag:
        type: string
      ref:
        type: string
      param:
        type: string
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: "Setup required directories"
        command: |
          mkdir -p /tmp/apache-cloudstack
          mkdir -p /tmp/.m2
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-m2
    - run:
        name: "Test Docker image"
        command: |
          docker run \
            --volume /tmp/apache-cloudstack:/mnt/build \
            --volume /tmp/.m2:/root/.m2 \
            --rm \
            khos2ow/cloudstack-rpm-builder:<<parameters.tag>> \
              --git-remote https://github.com/apache/cloudstack.git \
              --git-ref <<parameters.ref>> \
              --remove-first \
              <<parameters.param>>
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-m2
        paths:
          - /tmp/.m2

workflows:
  version: 2
  build:
    jobs:
    - centos6
    - test:
        name: test-centos6
        tag: centos6
        ref: refs/heads/4.13
        param: --distribution centos63
        requires:
        - centos6

    - centos7
    - test:
        name: test-centos7
        tag: centos7
        ref: refs/heads/4.13
        param: --distribution centos7
        requires:
        - centos7

    - latest
    - test:
        name: test-latest
        tag: centos7
        ref: refs/heads/4.13
        param: --distribution centos7
        requires:
        - latest

  # release:
  #   jobs:
  #   - centos6:
  #       filters:
  #         branches:
  #           only: master
  #           ignore: /.*/

  #   - centos7:
  #       filters:
  #         branches:
  #           only: master
  #           ignore: /.*/

  #   - latest:
  #       filters:
  #         branches:
  #           only: master
  #           ignore: /.*/

